window.ALL_SETS = {
  set1: [
    // UNIT I
    { unit: "Unit I", q: "Management is best defined as:", options: ['Ownership of business', 'Art of getting work done through others', 'Control of machines', 'Accounting activity'], answer: 1 },
    { unit: "Unit I", q: "Which function of management ensures work is carried out as planned?", options: ['Planning', 'Organizing', 'Controlling', 'Staffing'], answer: 2 },
    { unit: "Unit I", q: "Line and staff organization is preferred because it:", options: ['Eliminates staff authority', 'Combines specialization with unity of command', 'Avoids expert advice', 'Works only in small firms'], answer: 1 },
    { unit: "Unit I", q: "A company manufacturing a single product with small workforce should adopt:", options: ['Functional organization', 'Line organization', 'Line and staff organization', 'Matrix organization'], answer: 1 },
    { unit: "Unit I", q: "If supervisors are unable to take decisions independently, which management principle is violated?", options: ['Unity of direction', 'Authority and responsibility', 'Division of work', 'Scalar chain'], answer: 1 },
    { unit: "Unit I", q: "A manager motivating employees to achieve targets is performing which function?", options: ['Planning', 'Organizing', 'Directing', 'Controlling'], answer: 2 },
    
    // UNIT II
    { unit: "Unit II", q: "Which is a long-term source of finance?", options: ['Bank overdraft', 'Trade credit', 'Equity shares', 'Cash credit'], answer: 2 },
    { unit: "Unit II", q: "Debenture holders are called creditors because they:", options: ['Share profit', 'Have voting rights', 'Receive fixed interest', 'Bear maximum risk'], answer: 2 },
    { unit: "Unit II", q: "Break-even point indicates:", options: ['Maximum profit', 'No profit no loss', 'Minimum production', 'Fixed cost'], answer: 1 },
    { unit: "Unit II", q: "Fixed cost = ₹20,000, Contribution per unit = ₹10. Break-even quantity (units) is:", options: ['1,000', '2,000', '3,000', '4,000'], answer: 1 },
    { unit: "Unit II", q: "Annual demand = 4,000 units, Ordering cost = ₹100/order, Holding cost = ₹10/unit/year. EOQ is:", options: ['200 units', '283 units', '400 units', '500 units'], answer: 1 },
    { unit: "Unit II", q: "If fixed cost increases, break-even point will:", options: ['Decrease', 'Remain same', 'Increase', 'Become zero'], answer: 2 },
    { unit: "Unit II", q: "Capital used for purchase of raw material is:", options: ['Fixed capital', 'Reserve capital', 'Working capital', 'Share capital'], answer: 2 },
    
    // UNIT III
    { unit: "Unit III", q: "HRM stands for:", options: ['Human Relation Method', 'Human Resource Management', 'Human Recruitment Model', 'Human Regulation Mechanism'], answer: 1 },
    { unit: "Unit III", q: "Recruitment refers to:", options: ['Appointment of employees', 'Training of workers', 'Attracting potential employees', 'Selection of best candidate'], answer: 2 },
    { unit: "Unit III", q: "Which training method is conducted at actual workplace?", options: ['Vestibule training', 'Apprenticeship training', 'Lecture method', 'Case study'], answer: 1 },
    { unit: "Unit III", q: "Frequent accidents in a factory indicate need for:", options: ['Wage revision', 'Safety training', 'More supervisors', 'Marketing survey'], answer: 1 },
    { unit: "Unit III", q: "An employee injured during work should get compensation under:", options: ['Factory Act', 'ESI Act', 'Workmen Compensation Act', 'Minimum Wages Act'], answer: 2 },
    { unit: "Unit III", q: "Democratic supervision improves productivity because it:", options: ['Uses fear', 'Encourages worker participation', 'Centralizes power', 'Reduces communication'], answer: 1 },
    
    // UNIT IV
    { unit: "Unit IV", q: "Marketing primarily focuses on:", options: ['Production', 'Sales', 'Consumer needs', 'Profit'], answer: 2 },
    { unit: "Unit IV", q: "Which of the following is NOT a function of marketing?", options: ['Market research', 'Sales forecasting', 'Quality inspection', 'Advertising'], answer: 2 },
    { unit: "Unit IV", q: "ABC analysis classifies inventory based on:", options: ['Cost value', 'Size', 'Weight', 'Shelf life'], answer: 0 },
    { unit: "Unit IV", q: "Vital items in VED analysis require:", options: ['Minimum control', 'No control', 'Maximum control', 'Periodic control'], answer: 2 },
    { unit: "Unit IV", q: "Selling price is calculated by adding profit to:", options: ['Material cost only', 'Labor cost only', 'Total cost', 'Fixed cost only'], answer: 2 },
    { unit: "Unit IV", q: "Electricity charges in factory are treated as:", options: ['Direct cost', 'Selling overhead', 'Factory overhead', 'Office expense'], answer: 2 },
    
    // UNIT V
    { unit: "Unit V", q: "TQM stands for:", options: ['Total Quantity Management', 'Total Quality Management', 'Technical Quality Method', 'Total Quick Manufacturing'], answer: 1 },
    { unit: "Unit V", q: "Quality assurance focuses on:", options: ['Inspection only', 'Preventing defects', 'Rejecting products', 'Increasing cost'], answer: 1 },
    { unit: "Unit V", q: "5S technique was developed in:", options: ['USA', 'Germany', 'Japan', 'UK'], answer: 2 },
    { unit: "Unit V", q: "Continuous small improvements in work process is called:", options: ['Six Sigma', 'Kaizen', 'JIT', 'ISO'], answer: 1 },
    { unit: "Unit V", q: "ISO 9001:2015 is related to:", options: ['Environment management', 'Quality management system', 'Safety management', 'Energy management'], answer: 1 },
    
    // UNIT VI
    { unit: "Unit VI", q: "A project is a:", options: ['Routine activity', 'Temporary endeavor', 'Continuous process', 'Department'], answer: 1 },
    { unit: "Unit VI", q: "Scope creep means:", options: ['Scope reduction', 'Uncontrolled scope changes', 'Resource leveling', 'Cost cutting'], answer: 1 },
    { unit: "Unit VI", q: "Gantt chart is mainly used for:", options: ['Cost estimation', 'Scheduling activities', 'Quality control', 'Risk analysis'], answer: 1 },
    { unit: "Unit VI", q: "The longest path in a project network is called:", options: ['Short path', 'Critical path', 'Float path', 'Dummy path'], answer: 1 },
    { unit: "Unit VI", q: "PERT is preferred when activity time is:", options: ['Fixed', 'Known', 'Uncertain', 'Zero'], answer: 2 }
  ],
  
  set2: [
    // UNIT I
    { unit: "Unit I", q: "Management is concerned with:", options: ['Machines only', 'Men, money, materials & methods', 'Accounting only', 'Production only'], answer: 1 },
    { unit: "Unit I", q: "Planning mainly involves:", options: ['Execution', 'Future course of action', 'Motivation', 'Inspection'], answer: 1 },
    { unit: "Unit I", q: "Functional organization is suitable when:", options: ['Expert knowledge is required', 'Workers are unskilled', 'Business is small', 'Authority is centralized'], answer: 0 },
    { unit: "Unit I", q: "A government department normally follows:", options: ['Proprietorship', 'Partnership', 'Public sector ownership', 'Co-operative ownership'], answer: 2 },
    { unit: "Unit I", q: "Delay in decision-making occurs due to violation of:", options: ['Scalar chain', 'Unity of command', 'Authority', 'Discipline'], answer: 0 },
    { unit: "Unit I", q: "Issuing instructions to workers comes under:", options: ['Planning', 'Organizing', 'Directing', 'Controlling'], answer: 2 },
    
    // UNIT II
    { unit: "Unit II", q: "Shares represent:", options: ['Loan capital', 'Ownership capital', 'Temporary finance', 'Reserve fund'], answer: 1 },
    { unit: "Unit II", q: "Preference shareholders get:", options: ['Voting rights', 'Fixed dividend', 'Residual profit', 'No dividend'], answer: 1 },
    { unit: "Unit II", q: "Working capital is used for:", options: ['Land purchase', 'Machinery purchase', 'Daily operations', 'Building construction'], answer: 2 },
    { unit: "Unit II", q: "Fixed cost = ₹15,000, Contribution/unit = ₹5. BEP (units) =", options: ['2,000', '3,000', '4,000', '5,000'], answer: 1 },
    { unit: "Unit II", q: "EOQ helps to reduce:", options: ['Production cost', 'Inventory cost', 'Labour cost', 'Selling cost'], answer: 1 },
    { unit: "Unit II", q: "If ordering cost increases, EOQ will:", options: ['Decrease', 'Increase', 'Remain same', 'Become zero'], answer: 1 },
    { unit: "Unit II", q: "Capital invested in machinery is:", options: ['Working capital', 'Fixed capital', 'Reserve capital', 'Floating capital'], answer: 1 },
    
    // UNIT III
    { unit: "Unit III", q: "Selection means:", options: ['Attracting candidates', 'Choosing best candidate', 'Training workers', 'Promotion'], answer: 1 },
    { unit: "Unit III", q: "Motivation improves:", options: ['Absenteeism', 'Productivity', 'Accidents', 'Conflicts'], answer: 1 },
    { unit: "Unit III", q: "Safety training aims to:", options: ['Increase wages', 'Reduce accidents', 'Increase discipline', 'Reduce staff'], answer: 1 },
    { unit: "Unit III", q: "Accident due to unsafe condition can be prevented by:", options: ['Discipline', 'Machine guarding', 'Salary increase', 'Promotion'], answer: 1 },
    { unit: "Unit III", q: "Which act covers medical benefits?", options: ['Factory Act', 'ESI Act', 'Bonus Act', 'Minimum Wages Act'], answer: 1 },
    { unit: "Unit III", q: "Autocratic supervision results in:", options: ['High morale', 'Fear and low initiative', 'Participation', 'Innovation'], answer: 1 },
    
    // UNIT IV
    { unit: "Unit IV", q: "Market means:", options: ['Place of selling', 'Customers with purchasing power', 'Retail shop', 'Warehouse'], answer: 1 },
    { unit: "Unit IV", q: "Sales forecasting helps in:", options: ['Production planning', 'Quality control', 'Safety', 'Accounting'], answer: 0 },
    { unit: "Unit IV", q: "'A' items in ABC analysis require:", options: ['Least control', 'Moderate control', 'Strict control', 'No control'], answer: 2 },
    { unit: "Unit IV", q: "Spare parts are classified under:", options: ['ABC', 'VED', 'EOQ', 'FIFO'], answer: 1 },
    { unit: "Unit IV", q: "Indirect labour cost includes:", options: ['Machine operator', 'Supervisor', 'Fitter', 'Turner'], answer: 1 },
    { unit: "Unit IV", q: "Factory rent is:", options: ['Direct cost', 'Selling overhead', 'Factory overhead', 'Office expense'], answer: 2 },
    
    // UNIT V
    { unit: "Unit V", q: "Quality control means:", options: ['Inspection after production', 'Maintaining quality standards', 'Rejecting goods', 'Increasing cost'], answer: 1 },
    { unit: "Unit V", q: "Quality circle consists of:", options: ['Managers only', 'Workers only', 'Workers & supervisors', 'Customers'], answer: 2 },
    { unit: "Unit V", q: "Six Sigma aims at:", options: ['Zero defects', 'More profit', 'Faster delivery', 'Automation'], answer: 0 },
    { unit: "Unit V", q: "JIT helps in reducing:", options: ['Inventory', 'Labour', 'Sales', 'Quality'], answer: 0 },
    { unit: "Unit V", q: "ISO 14001 is related to:", options: ['Quality', 'Safety', 'Environment', 'Energy'], answer: 2 },
    
    // UNIT VI
    { unit: "Unit VI", q: "Project objectives should be:", options: ['Vague', 'Clear', 'Hidden', 'Flexible'], answer: 1 },
    { unit: "Unit VI", q: "CPM is suitable when activity time is:", options: ['Certain', 'Uncertain', 'Random', 'Zero'], answer: 0 },
    { unit: "Unit VI", q: "PERT uses:", options: ['One time estimate', 'Two time estimates', 'Three time estimates', 'No estimates'], answer: 2 },
    { unit: "Unit VI", q: "Activities with zero float lie on:", options: ['Dummy path', 'Critical path', 'Short path', 'Free path'], answer: 1 },
    { unit: "Unit VI", q: "Resource leveling is used to:", options: ['Increase cost', 'Balance resources', 'Reduce quality', 'Delay project'], answer: 1 }
  ],
  
  set3: [
    // UNIT I
    { unit: "Unit I", q: "Administration is mainly concerned with:", options: ['Execution of plans', 'Policy formulation', 'Supervision', 'Motivation'], answer: 1 },
    { unit: "Unit I", q: "Partnership form of ownership is limited by:", options: ['Capital availability', 'Unlimited liability', 'Government control', 'Skilled manpower'], answer: 1 },
    { unit: "Unit I", q: "Line authority flows from:", options: ['Bottom to top', 'Staff to line', 'Top to bottom', 'Workers to managers'], answer: 2 },
    { unit: "Unit I", q: "A firm needing expert advice without disturbing authority should adopt:", options: ['Line organization', 'Functional organization', 'Line and staff organization', 'Committee organization'], answer: 2 },
    { unit: "Unit I", q: "When one employee receives orders from many supervisors, it violates:", options: ['Unity of direction', 'Unity of command', 'Discipline', 'Equity'], answer: 1 },
    { unit: "Unit I", q: "Fixing targets before starting work is part of:", options: ['Organizing', 'Planning', 'Directing', 'Controlling'], answer: 1 },
    
    // UNIT II
    { unit: "Unit II", q: "Medium-term finance is required for:", options: ['Daily expenses', 'Expansion', 'Wages payment', 'Raw material purchase'], answer: 1 },
    { unit: "Unit II", q: "Shares differ from debentures because shares:", options: ['Have fixed return', 'Are repayable', 'Carry ownership', 'Are secured'], answer: 2 },
    { unit: "Unit II", q: "Break-even analysis helps management in:", options: ['Tax calculation', 'Decision making', 'Wage fixation', 'Recruitment'], answer: 1 },
    { unit: "Unit II", q: "Fixed cost = ₹25,000, Contribution/unit = ₹25. BEP (units) =", options: ['500', '1,000', '1,500', '2,000'], answer: 1 },
    { unit: "Unit II", q: "If EOQ is 400 units and annual demand is 4,000 units, number of orders per year is:", options: ['5', '8', '10', '12'], answer: 2 },
    { unit: "Unit II", q: "Increase in selling price (cost constant) will:", options: ['Increase BEP', 'Decrease BEP', 'Not affect BEP', 'Eliminate fixed cost'], answer: 1 },
    { unit: "Unit II", q: "Cash kept for emergency needs is:", options: ['Fixed capital', 'Floating capital', 'Working capital', 'Share capital'], answer: 2 },
    
    // UNIT III
    { unit: "Unit III", q: "Placement refers to:", options: ['Job rotation', 'Assigning job to employee', 'Promotion', 'Training'], answer: 1 },
    { unit: "Unit III", q: "Which is a financial motivation?", options: ['Promotion', 'Bonus', 'Recognition', 'Responsibility'], answer: 1 },
    { unit: "Unit III", q: "Labour welfare improves:", options: ['Absenteeism', 'Employee morale', 'Accident rate', 'Conflict'], answer: 1 },
    { unit: "Unit III", q: "Repeated absenteeism can be controlled by:", options: ['Strict punishment', 'Better motivation', 'Increased supervision', 'More machines'], answer: 1 },
    { unit: "Unit III", q: "Safety posters mainly help in:", options: ['Training', 'Awareness', 'Inspection', 'Compensation'], answer: 1 },
    { unit: "Unit III", q: "Laissez-faire supervision results in:", options: ['High discipline', 'No control', 'High fear', 'Centralization'], answer: 1 },
    
    // UNIT IV
    { unit: "Unit IV", q: "Consumer behavior studies:", options: ['Producer needs', 'Buying habits', 'Costing', 'Storage'], answer: 1 },
    { unit: "Unit IV", q: "Advertising mainly aims to:", options: ['Reduce cost', 'Inform customers', 'Improve quality', 'Control inventory'], answer: 1 },
    { unit: "Unit IV", q: "Market survey collects:", options: ['Internal data', 'Customer data', 'Financial data', 'Inventory data'], answer: 1 },
    { unit: "Unit IV", q: "Items critical for production but low cost fall under:", options: ['A category', 'B category', 'C category', 'V category'], answer: 3 },
    { unit: "Unit IV", q: "Direct material cost includes:", options: ['Lubricants', 'Packing material', 'Raw material', 'Office stationery'], answer: 2 },
    { unit: "Unit IV", q: "Wages of storekeeper are:", options: ['Direct labour', 'Factory overhead', 'Selling expense', 'Office expense'], answer: 1 },
    
    // UNIT V
    { unit: "Unit V", q: "Quality conformance means:", options: ['Meeting standards', 'Inspection', 'Rework', 'Scrap'], answer: 0 },
    { unit: "Unit V", q: "Quality circle meetings are held to:", options: ['Increase wages', 'Solve work problems', 'Inspect goods', 'Reduce staff'], answer: 1 },
    { unit: "Unit V", q: "Six Sigma reduces defects by:", options: ['Trial and error', 'Statistical tools', 'Inspection only', 'Automation'], answer: 1 },
    { unit: "Unit V", q: "Sorting and removing unwanted items is:", options: ['Seiton', 'Seiri', 'Seiso', 'Seiketsu'], answer: 1 },
    { unit: "Unit V", q: "ISO certification mainly improves:", options: ['Customer confidence', 'Product price', 'Inventory', 'Advertising'], answer: 0 },
    
    // UNIT VI
    { unit: "Unit VI", q: "Project scope defines:", options: ['Project cost', 'Project boundaries', 'Project team', 'Project risk'], answer: 1 },
    { unit: "Unit VI", q: "Stakeholders include:", options: ['Only customers', 'Only managers', 'All affected parties', 'Only workers'], answer: 2 },
    { unit: "Unit VI", q: "Gantt chart shows:", options: ['Cost variation', 'Activity vs time', 'Quality level', 'Risk level'], answer: 1 },
    { unit: "Unit VI", q: "Delay in critical activity will:", options: ['Not affect project', 'Delay project completion', 'Reduce cost', 'Increase float'], answer: 1 },
    { unit: "Unit VI", q: "CPM is preferred when project activities are:", options: ['Uncertain', 'Probabilistic', 'Deterministic', 'Random'], answer: 2 }
  ],
  
  set4: [
    // UNIT I
    { unit: "Unit I", q: "Management deals mainly with:", options: ['Planning machines', 'Coordinating resources', 'Accounting records', 'Manufacturing goods'], answer: 1 },
    { unit: "Unit I", q: "Proprietorship is limited mainly due to:", options: ['Large capital', 'Unlimited liability', 'Government support', 'Skilled labor'], answer: 1 },
    { unit: "Unit I", q: "Functional organization violates which principle?", options: ['Equity', 'Unity of command', 'Discipline', 'Initiative'], answer: 1 },
    { unit: "Unit I", q: "A growing firm requiring specialists but clear authority should choose:", options: ['Line', 'Functional', 'Line and staff', 'Project'], answer: 2 },
    { unit: "Unit I", q: "When authority is not matched with responsibility, it leads to:", options: ['Efficiency', 'Conflict', 'Coordination', 'Motivation'], answer: 1 },
    { unit: "Unit I", q: "Comparing alternatives before action is part of:", options: ['Planning', 'Directing', 'Controlling', 'Staffing'], answer: 0 },
    
    // UNIT II
    { unit: "Unit II", q: "Debentures are issued to raise:", options: ['Short-term finance', 'Ownership capital', 'Loan capital', 'Reserve fund'], answer: 2 },
    { unit: "Unit II", q: "Preference shareholders get priority in:", options: ['Voting', 'Management', 'Dividend payment', 'Risk bearing'], answer: 2 },
    { unit: "Unit II", q: "Break-even chart shows relation between:", options: ['Cost & time', 'Cost & output', 'Profit & tax', 'Price & demand'], answer: 1 },
    { unit: "Unit II", q: "Fixed cost = ₹18,000, Contribution per unit = ₹12. BEP (units) =", options: ['1,000', '1,200', '1,500', '2,000'], answer: 1 },
    { unit: "Unit II", q: "Annual demand = 3,600 units, EOQ = 600 units. Orders per year =", options: ['4', '5', '6', '8'], answer: 2 },
    { unit: "Unit II", q: "Reduction in fixed cost will:", options: ['Increase BEP', 'Decrease BEP', 'Not affect BEP', 'Increase loss'], answer: 1 },
    { unit: "Unit II", q: "Capital used for paying wages is:", options: ['Fixed capital', 'Working capital', 'Reserve capital', 'Equity capital'], answer: 1 },
    
    // UNIT III
    { unit: "Unit III", q: "Motivation can be defined as:", options: ['Punishment', 'Inner drive to work', 'Supervision', 'Control'], answer: 1 },
    { unit: "Unit III", q: "Training mainly improves:", options: ['Absenteeism', 'Skill level', 'Accidents', 'Conflicts'], answer: 1 },
    { unit: "Unit III", q: "Safety engineering focuses on:", options: ['Cost reduction', 'Accident prevention', 'Production increase', 'Sales'], answer: 1 },
    { unit: "Unit III", q: "High labour turnover can be reduced by:", options: ['Wage cuts', 'Welfare facilities', 'Strict rules', 'More supervision'], answer: 1 },
    { unit: "Unit III", q: "Factory Act, 1948 mainly deals with:", options: ['Wages', 'Safety & welfare', 'Trade disputes', 'Bonus'], answer: 1 },
    { unit: "Unit III", q: "Supervisor acting as link between workers and management performs role of:", options: ['Leader', 'Communicator', 'Inspector', 'Accountant'], answer: 1 },
    
    // UNIT IV
    { unit: "Unit IV", q: "Marketing environment includes:", options: ['Internal factors only', 'External factors only', 'Both internal and external', 'Production factors'], answer: 2 },
    { unit: "Unit IV", q: "Sales promotion differs from advertising because it is:", options: ['Long-term', 'Personal', 'Short-term', 'Expensive'], answer: 2 },
    { unit: "Unit IV", q: "ABC analysis is also called:", options: ['Selective inventory control', 'Random inventory control', 'FIFO method', 'LIFO method'], answer: 0 },
    { unit: "Unit IV", q: "Items having low cost but essential for operation are:", options: ['A items', 'B items', 'C items', 'V items'], answer: 3 },
    { unit: "Unit IV", q: "Wages of production workers are treated as:", options: ['Indirect labour', 'Direct labour', 'Factory overhead', 'Office expense'], answer: 1 },
    { unit: "Unit IV", q: "Advertising expense is classified as:", options: ['Factory cost', 'Selling overhead', 'Office overhead', 'Direct cost'], answer: 1 },
    
    // UNIT V
    { unit: "Unit V", q: "Quality assurance is concerned with:", options: ['Detection of defects', 'Prevention of defects', 'Repair work', 'Scrap disposal'], answer: 1 },
    { unit: "Unit V", q: "TQM involves participation of:", options: ['Only workers', 'Only managers', 'Only inspectors', 'Everyone in organization'], answer: 3 },
    { unit: "Unit V", q: "5S improves workplace by:", options: ['Increasing machines', 'Systematic arrangement', 'Increasing cost', 'Automation'], answer: 1 },
    { unit: "Unit V", q: "Cleaning workplace regularly refers to:", options: ['Seiri', 'Seiton', 'Seiso', 'Shitsuke'], answer: 2 },
    { unit: "Unit V", q: "ISO standards mainly help in:", options: ['Export promotion', 'Quality consistency', 'Cost reduction only', 'Profit sharing'], answer: 1 },
    
    // UNIT VI
    { unit: "Unit VI", q: "Project management deals with:", options: ['Routine work', 'Temporary activities', 'Repetitive jobs', 'Production planning'], answer: 1 },
    { unit: "Unit VI", q: "Project planning is done to:", options: ['Delay work', 'Ensure timely completion', 'Increase cost', 'Reduce scope'], answer: 1 },
    { unit: "Unit VI", q: "CPM focuses mainly on:", options: ['Cost uncertainty', 'Time scheduling', 'Quality inspection', 'Human relations'], answer: 1 },
    { unit: "Unit VI", q: "Slack time in non-critical activity can be:", options: ['Ignored', 'Utilized', 'Removed', 'Increased fixed'], answer: 1 },
    { unit: "Unit VI", q: "PERT is most suitable for:", options: ['Routine projects', 'Research projects', 'Small jobs', 'Repetitive work'], answer: 1 }
  ],
  
  set5: [
    // UNIT I
    { unit: "Unit I", q: "Management principles were given by:", options: ['Taylor', 'Fayol', 'Mayo', 'Maslow'], answer: 1 },
    { unit: "Unit I", q: "Co-operative organization works on principle of:", options: ['Profit maximization', 'Mutual help', 'Government control', 'Private ownership'], answer: 1 },
    { unit: "Unit I", q: "Scalar chain refers to:", options: ['Wage structure', 'Line of authority', 'Job rotation', 'Communication barrier'], answer: 1 },
    { unit: "Unit I", q: "If quick decisions are required, best structure is:", options: ['Functional', 'Line', 'Matrix', 'Committee'], answer: 1 },
    { unit: "Unit I", q: "Lack of coordination results in:", options: ['Efficiency', 'Duplication of work', 'Motivation', 'Discipline'], answer: 1 },
    { unit: "Unit I", q: "Comparing planned performance with actual is part of:", options: ['Planning', 'Organizing', 'Controlling', 'Staffing'], answer: 2 },
    
    // UNIT II
    { unit: "Unit II", q: "Capital invested by owners is called:", options: ['Loan capital', 'Working capital', 'Share capital', 'Reserve capital'], answer: 2 },
    { unit: "Unit II", q: "Debenture interest is paid:", options: ['After profit', 'Before profit', 'When profit exists', 'Only yearly'], answer: 1 },
    { unit: "Unit II", q: "BEP analysis is useful for:", options: ['Production planning', 'Pricing decisions', 'Cost control', 'All of the above'], answer: 3 },
    { unit: "Unit II", q: "Fixed cost = ₹30,000, Contribution/unit = ₹15. BEP (units) =", options: ['1,500', '2,000', '2,500', '3,000'], answer: 1 },
    { unit: "Unit II", q: "EOQ = 500 units, Annual demand = 5,000 units. Orders per year =", options: ['5', '8', '10', '12'], answer: 2 },
    { unit: "Unit II", q: "Increase in variable cost will:", options: ['Reduce BEP', 'Increase BEP', 'Eliminate BEP', 'Not affect BEP'], answer: 1 },
    { unit: "Unit II", q: "Capital used to buy land is:", options: ['Working capital', 'Fixed capital', 'Circulating capital', 'Reserve capital'], answer: 1 },
    
    // UNIT III
    { unit: "Unit III", q: "Industrial relations deal with relations between:", options: ['Employer and customer', 'Employer and employee', 'Worker and worker', 'Management and supplier'], answer: 1 },
    { unit: "Unit III", q: "Training is required mainly due to:", options: ['Promotion', 'Technological changes', 'Absenteeism', 'Retirement'], answer: 1 },
    { unit: "Unit III", q: "Accident prevention reduces:", options: ['Production', 'Compensation cost', 'Quality', 'Sales'], answer: 1 },
    { unit: "Unit III", q: "Lack of motivation results in:", options: ['High productivity', 'Labour unrest', 'Innovation', 'Skill improvement'], answer: 1 },
    { unit: "Unit III", q: "ESI Act mainly benefits employees by providing:", options: ['Bonus', 'Medical facilities', 'Pension', 'Promotion'], answer: 1 },
    { unit: "Unit III", q: "Supervisor giving freedom to workers is following:", options: ['Autocratic style', 'Democratic style', 'Laissez-faire style', 'Bureaucratic style'], answer: 2 },

    // UNIT IV
{ unit: "Unit IV", q: "Marketing mix consists of:", options: ['2 P\'s', '3 P\'s', '4 P\'s', '5 P\'s'], answer: 2 },
{ unit: "Unit IV", q: "Market research helps in:", options: ['Cost control', 'Decision making', 'Wage fixation', 'Safety'], answer: 1 },
{ unit: "Unit IV", q: "C items in ABC analysis represent:", options: ['High value', 'Moderate value', 'Low value', 'Critical items'], answer: 2 },
{ unit: "Unit IV", q: "Essential spare parts fall under:", options: ['A category', 'B category', 'C category', 'V category'], answer: 3 },
{ unit: "Unit IV", q: "Cost of raw material used directly in product is:", options: ['Indirect cost', 'Direct cost', 'Overhead', 'Selling cost'], answer: 1 },
{ unit: "Unit IV", q: "Office clerk salary is treated as:", options: ['Factory overhead', 'Direct labour', 'Office overhead', 'Selling cost'], answer: 2 },

// UNIT V
{ unit: "Unit V", q: "Six Sigma allows maximum defects of:", options: ['3.4 per million', '34 per million', '340 per million', 'Zero only'], answer: 0 },
{ unit: "Unit V", q: "TQM emphasizes:", options: ['Inspection', 'Customer satisfaction', 'Automation', 'Cost cutting'], answer: 1 },
{ unit: "Unit V", q: "ISO certification is:", options: ['Mandatory', 'Voluntary', 'Illegal', 'Temporary'], answer: 1 },
{ unit: "Unit V", q: "Standardizing best practices is:", options: ['Seiri', 'Seiton', 'Seiketsu', 'Shitsuke'], answer: 2 },
{ unit: "Unit V", q: "Kaizen mainly improves:", options: ['Sudden change', 'Continuous improvement', 'Inspection', 'Rejection'], answer: 1 },

// UNIT VI
{ unit: "Unit VI", q: "CPM stands for:", options: ['Cost Planning Method', 'Critical Path Method', 'Continuous Project Model', 'Cost Performance Measure'], answer: 1 },
{ unit: "Unit VI", q: "PERT is useful for:", options: ['Certain activities', 'Uncertain activities', 'Repetitive work', 'Office work'], answer: 1 },
{ unit: "Unit VI", q: "Gantt chart helps in:", options: ['Budgeting', 'Scheduling', 'Inspection', 'Motivation'], answer: 1 },
{ unit: "Unit VI", q: "If a non-critical activity is delayed within float time:", options: ['Project delays', 'Project unaffected', 'Cost doubles', 'Scope increases'], answer: 1 },
{ unit: "Unit VI", q: "Project completion time is decided by:", options: ['Shortest path', 'Average path', 'Critical path', 'Random path'], answer: 2 }],

// UNIT I - Introduction to Management
  unit1: [
    { unit: "Unit I", q: "Management is primarily a process of:", options: ['Earning profit', 'Planning, organizing, directing and controlling', 'Policy making only', 'Risk bearing'], answer: 1 },
    { unit: "Unit I", q: "Administration mainly deals with:", options: ['Execution of work', 'Supervising workers', 'Policy formulation', 'Motivation'], answer: 2 },
    { unit: "Unit I", q: "Which form of ownership is owned by a single person?", options: ['Partnership', 'Joint stock company', 'Proprietorship', 'Cooperative society'], answer: 2 },
    { unit: "Unit I", q: "The person who undertakes risk in business is called:", options: ['Manager', 'Administrator', 'Entrepreneur', 'Supervisor'], answer: 2 },
    { unit: "Unit I", q: "Which organization has a separate legal entity?", options: ['Proprietorship', 'Partnership', 'Joint stock company', 'Sole trading concern'], answer: 2 },
    { unit: "Unit I", q: "Management is called a continuous process because:", options: ['It is done only once', 'It ends with planning', 'Functions are performed repeatedly', 'It focuses only on profit'], answer: 2 },
    { unit: "Unit I", q: "Which of the following is NOT a feature of proprietorship?", options: ['Easy formation', 'Unlimited liability', 'Separate legal entity', 'Full control'], answer: 2 },
    { unit: "Unit I", q: "Advantage of partnership over proprietorship is:", options: ['Limited liability', 'Better secrecy', 'More capital availability', 'Single ownership'], answer: 2 },
    { unit: "Unit I", q: "One major disadvantage of joint stock company is:", options: ['Limited capital', 'Unlimited liability', 'Complex formation', 'Lack of continuity'], answer: 2 },
    { unit: "Unit I", q: "Entrepreneurship mainly emphasizes:", options: ['Routine supervision', 'Policy making', 'Innovation and risk taking', 'Government regulation'], answer: 2 },
    { unit: "Unit I", q: "Management differs from administration because management:", options: ['Determines objectives', 'Performs execution', 'Frames policies', 'Operates at top level only'], answer: 1 },
    { unit: "Unit I", q: "Ramesh starts a small grocery shop using his own savings and manages everything himself. This form of ownership is:", options: ['Partnership', 'Joint stock company', 'Proprietorship', 'Cooperative'], answer: 2 },
    { unit: "Unit I", q: "A business wants to raise huge capital and limit the liability of owners. Which form is most suitable?", options: ['Proprietorship', 'Partnership', 'Joint stock company', 'Sole trade'], answer: 2 },
    { unit: "Unit I", q: "A firm closes down due to the death of its only owner. Which limitation is highlighted?", options: ['Limited capital', 'Lack of continuity', 'Unlimited liability', 'Lack of secrecy'], answer: 1 },
    { unit: "Unit I", q: "A person introduces a new product in the market by taking financial risk. His role best represents:", options: ['Manager', 'Administrator', 'Entrepreneur', 'Shareholder'], answer: 2 },
    { unit: "Unit I", q: "A co-operative society is based on the principle of:", options: ['Profit maximization', 'Mutual help', 'Government control', 'Private ownership'], answer: 1 },
    { unit: "Unit I", q: "Public sector enterprises are owned by:", options: ['Private individuals', 'Shareholders', 'Government', 'Partners'], answer: 2 },
    { unit: "Unit I", q: "Which enterprise follows 'one member one vote'?", options: ['Joint stock company', 'Partnership', 'Co-operative society', 'Proprietorship'], answer: 2 },
    { unit: "Unit I", q: "Government undertakings mainly work for:", options: ['Profit motive', 'Public welfare', 'Shareholder benefit', 'Export promotion'], answer: 1 },
    { unit: "Unit I", q: "Which sector is suitable for essential public services?", options: ['Private sector', 'Co-operative sector', 'Public sector', 'Partnership'], answer: 2 },
    { unit: "Unit I", q: "Main objective of co-operative sector is:", options: ['Profit earning', 'Capital formation', 'Service to members', 'Monopoly creation'], answer: 2 },
    { unit: "Unit I", q: "Which is a limitation of public sector enterprises?", options: ['Limited capital', 'Political interference', 'Democratic management', 'Mutual help'], answer: 1 },
    { unit: "Unit I", q: "Government undertakings are preferred in strategic industries because:", options: ['They provide high profit', 'They ensure national security', 'They are easy to form', 'They avoid regulations'], answer: 1 },
    { unit: "Unit I", q: "Which of the following is NOT an advantage of co-operatives?", options: ['Democratic control', 'Limited liability', 'Efficient professional management', 'Government support'], answer: 2 },
    { unit: "Unit I", q: "Public sector enterprises are mainly motivated by:", options: ['Profit', 'Market competition', 'Public service', 'Private ownership'], answer: 2 },
    { unit: "Unit I", q: "Slow decision making in public sector is due to:", options: ['Democratic control', 'Bureaucratic structure', 'Lack of capital', 'Limited liability'], answer: 1 },
    { unit: "Unit I", q: "Farmers form a society to buy fertilizers at low cost and share benefits equally. This is an example of:", options: ['Partnership', 'Joint stock company', 'Co-operative society', 'Public enterprise'], answer: 2 },
    { unit: "Unit I", q: "A business providing railway transport services should belong to:", options: ['Proprietorship', 'Partnership', 'Public sector', 'Co-operative sector'], answer: 2 },
    { unit: "Unit I", q: "An enterprise owned by the government to ensure national development is called:", options: ['Private company', 'Co-operative', 'Government undertaking', 'Partnership'], answer: 2 },
    { unit: "Unit I", q: "Which form is MOST suitable when profit is not the primary objective?", options: ['Proprietorship', 'Joint stock company', 'Public sector', 'Partnership'], answer: 2 },
    { unit: "Unit I", q: "In line organization, authority flows:", options: ['Horizontally', 'Diagonally', 'Vertically', 'Functionally'], answer: 2 },
    { unit: "Unit I", q: "Which organization follows unity of command strictly?", options: ['Functional', 'Line', 'Matrix', 'Committee'], answer: 1 },
    { unit: "Unit I", q: "Specialists are given authority in:", options: ['Line organization', 'Line & staff organization', 'Functional organization', 'Committee organization'], answer: 2 },
    { unit: "Unit I", q: "Staff authority is mainly:", options: ['Commanding', 'Advisory', 'Disciplinary', 'Financial'], answer: 1 },
    { unit: "Unit I", q: "Functional organization was developed by:", options: ['Fayol', 'Taylor', 'Mayo', 'Weber'], answer: 1 },
    { unit: "Unit I", q: "Main advantage of line organization is:", options: ['Specialization', 'Flexibility', 'Quick decision making', 'Expert advice'], answer: 2 },
    { unit: "Unit I", q: "Unity of command is violated in functional organization because:", options: ['Authority is centralized', 'Workers get orders from many specialists', 'No line managers exist', 'Decision making is fast'], answer: 1 },
    { unit: "Unit I", q: "Which is NOT a limitation of line & staff organization?", options: ['Conflict between line and staff', 'High cost', 'Clear authority', 'Delay in decisions'], answer: 2 },
    { unit: "Unit I", q: "Functional organization is most suitable for:", options: ['Small retail shop', 'Cottage industry', 'Large manufacturing concern', 'Small workshop'], answer: 2 },
    { unit: "Unit I", q: "Line & staff organization improves efficiency because:", options: ['Staff replaces line managers', 'Line managers receive expert advice', 'Authority is decentralized', 'Workers have no superior'], answer: 1 },
    { unit: "Unit I", q: "Which organization gives maximum specialization?", options: ['Line', 'Functional', 'Line & staff', 'Committee'], answer: 1 },
    { unit: "Unit I", q: "A small workshop where the owner takes all decisions should adopt:", options: ['Functional organization', 'Line organization', 'Line & staff organization', 'Committee organization'], answer: 1 },
    { unit: "Unit I", q: "A factory where workers receive instructions from production, quality, and maintenance experts follows:", options: ['Line', 'Line & staff', 'Functional', 'Committee'], answer: 2 },
    { unit: "Unit I", q: "An enterprise wants expert advice without losing unity of command. Best structure is:", options: ['Line', 'Functional', 'Line & staff', 'Matrix'], answer: 2 },
    { unit: "Unit I", q: "Conflict between advisory and executive roles occurs in:", options: ['Line organization', 'Functional organization', 'Line & staff organization', 'Committee organization'], answer: 2 },
    { unit: "Unit I", q: "Which is the first function of management?", options: ['Planning', 'Forecasting', 'Organizing', 'Controlling'], answer: 1 },
    { unit: "Unit I", q: "Selecting the best alternative is called:", options: ['Planning', 'Organizing', 'Decision making', 'Coordinating'], answer: 2 },
    { unit: "Unit I", q: "Which function deals with future uncertainty?", options: ['Organizing', 'Forecasting', 'Directing', 'Controlling'], answer: 1 },
    { unit: "Unit I", q: "Measuring performance against standards is:", options: ['Planning', 'Controlling', 'Directing', 'Motivating'], answer: 1 },
    { unit: "Unit I", q: "Integration of activities is known as:", options: ['Motivation', 'Coordination', 'Organization', 'Direction'], answer: 1 },
    { unit: "Unit I", q: "Planning is important because it:", options: ['Increases uncertainty', 'Eliminates coordination', 'Provides direction', 'Delays decisions'], answer: 2 },
    { unit: "Unit I", q: "Organizing mainly involves:", options: ['Selecting alternatives', 'Predicting future', 'Division of work', 'Giving incentives'], answer: 2 },
    { unit: "Unit I", q: "Motivation improves performance by:", options: ['Increasing supervision', 'Satisfying employee needs', 'Creating pressure', 'Controlling behavior'], answer: 1 },
    { unit: "Unit I", q: "Which function ensures unity of action?", options: ['Organizing', 'Directing', 'Coordinating', 'Controlling'], answer: 2 },
    { unit: "Unit I", q: "Controlling is ineffective without:", options: ['Coordination', 'Planning', 'Motivation', 'Direction'], answer: 1 },
    { unit: "Unit I", q: "Directing includes all EXCEPT:", options: ['Leadership', 'Supervision', 'Communication', 'Planning'], answer: 3 },
    { unit: "Unit I", q: "A manager predicts future demand before fixing production targets. This is:", options: ['Planning', 'Forecasting', 'Controlling', 'Decision making'], answer: 1 },
    { unit: "Unit I", q: "Employees are encouraged with bonuses to improve productivity. This function is:", options: ['Directing', 'Coordinating', 'Motivating', 'Controlling'], answer: 2 },
    { unit: "Unit I", q: "Actual output is less than standard output and corrective action is taken. This shows:", options: ['Planning', 'Organizing', 'Directing', 'Controlling'], answer: 3 },
    { unit: "Unit I", q: "Different departments work in harmony to achieve goals. This reflects:", options: ['Motivation', 'Coordination', 'Planning', 'Decision making'], answer: 1 },
    { unit: "Unit I", q: "Principles of management were given by:", options: ['Taylor', 'Fayol', 'Weber', 'Mayo'], answer: 1 },
    { unit: "Unit I", q: "Receiving orders from only one superior is:", options: ['Unity of direction', 'Unity of command', 'Discipline', 'Order'], answer: 1 },
    { unit: "Unit I", q: "Which level sets organizational objectives?", options: ['Lower', 'Middle', 'Top', 'Supervisory'], answer: 2 },
    { unit: "Unit I", q: "Scalar chain refers to:", options: ['Wage system', 'Line of authority', 'Motivation', 'Team spirit'], answer: 1 },
    { unit: "Unit I", q: "Foremen and supervisors belong to:", options: ['Top level', 'Middle level', 'Lower level', 'Executive level'], answer: 2 },
    { unit: "Unit I", q: "Division of work improves efficiency because it:", options: ['Increases workload', 'Promotes specialization', 'Reduces responsibility', 'Delays work'], answer: 1 },
    { unit: "Unit I", q: "Unity of direction means:", options: ['One boss per employee', 'One plan for one objective', 'Centralized authority', 'Equal authority'], answer: 1 },
    { unit: "Unit I", q: "Stability of tenure is important because it:", options: ['Reduces salary', 'Increases turnover', 'Improves efficiency', 'Creates conflict'], answer: 2 },
    { unit: "Unit I", q: "Middle management mainly acts as:", options: ['Policy maker', 'Link between top and lower', 'Supervisory authority', 'Owner'], answer: 1 },
    { unit: "Unit I", q: "Equity in management refers to:", options: ['Equal pay', 'Fair treatment', 'Profit sharing', 'Discipline'], answer: 1 },
    { unit: "Unit I", q: "Which function is mainly performed by lower management?", options: ['Policy making', 'Strategic planning', 'Supervision', 'Long-term control'], answer: 2 },
    { unit: "Unit I", q: "An employee receiving instructions from two managers violates:", options: ['Discipline', 'Unity of direction', 'Unity of command', 'Equity'], answer: 2 },
    { unit: "Unit I", q: "A CEO deciding company expansion strategy represents:", options: ['Lower management', 'Middle management', 'Top management', 'Supervisory level'], answer: 2 },
    { unit: "Unit I", q: "A department head coordinating activities of workers is part of:", options: ['Top level', 'Middle level', 'Lower level', 'Board'], answer: 1 },
    { unit: "Unit I", q: "Encouraging employees to suggest improvements relates to:", options: ['Discipline', 'Initiative', 'Order', 'Centralization'], answer: 1 },
  ],

  // UNIT II - Finance
  unit2: [
    { unit: "Unit II", q: "Finance is mainly required for:", options: ['Only profit distribution', 'Business activities', 'Wage reduction', 'Tax evasion'], answer: 1 },
    { unit: "Unit II", q: "Sources used for day-to-day operations are:", options: ['Long-term', 'Medium-term', 'Short-term', 'Equity'], answer: 2 },
    { unit: "Unit II", q: "Trade credit is a source of:", options: ['Long-term finance', 'Medium-term finance', 'Short-term finance', 'Permanent finance'], answer: 2 },
    { unit: "Unit II", q: "Equity shares are:", options: ['Short-term source', 'Medium-term source', 'Long-term source', 'Temporary finance'], answer: 2 },
    { unit: "Unit II", q: "Purchase of machinery is generally financed by:", options: ['Short-term sources', 'Medium-term sources', 'Trade credit', 'Cash credit'], answer: 1 },
    { unit: "Unit II", q: "Working capital refers to funds used for:", options: ['Fixed assets', 'Long-term investments', 'Daily operations', 'Expansion only'], answer: 2 },
    { unit: "Unit II", q: "Which is NOT a short-term source of finance?", options: ['Bank overdraft', 'Trade credit', 'Equity shares', 'Bills discounting'], answer: 2 },
    { unit: "Unit II", q: "Medium-term finance is suitable for:", options: ['Paying wages', 'Buying raw material', 'Purchasing machinery', 'Paying taxes'], answer: 2 },
    { unit: "Unit II", q: "Long-term finance is mainly used for:", options: ['Working capital', 'Fixed assets', 'Salary payment', 'Office expenses'], answer: 1 },
    { unit: "Unit II", q: "A limitation of short-term finance is:", options: ['Ownership dilution', 'High interest burden', 'Long repayment period', 'Low flexibility'], answer: 1 },
    { unit: "Unit II", q: "Debentures are a source of:", options: ['Short-term finance', 'Medium-term finance', 'Long-term finance', 'Internal finance'], answer: 2 },
    { unit: "Unit II", q: "A firm needs money to pay wages and electricity bills. Best source is:", options: ['Equity shares', 'Debentures', 'Bank overdraft', 'Long-term loan'], answer: 2 },
    { unit: "Unit II", q: "An enterprise planning to expand plant capacity should use:", options: ['Trade credit', 'Cash credit', 'Long-term finance', 'Bills discounting'], answer: 2 },
    { unit: "Unit II", q: "Funds required to meet unexpected expenses are classified as:", options: ['Fixed capital', 'Working capital', 'Share capital', 'Reserve capital'], answer: 1 },
    { unit: "Unit II", q: "A business purchasing equipment through instalments is using:", options: ['Trade credit', 'Hire purchase', 'Equity finance', 'Cash credit'], answer: 1 },
    { unit: "Unit II", q: "A share represents:", options: ['Loan capital', 'Ownership capital', 'Reserve fund', 'Fixed asset'], answer: 1 },
    { unit: "Unit II", q: "Holders of debentures are:", options: ['Owners', 'Partners', 'Creditors', 'Managers'], answer: 2 },
    { unit: "Unit II", q: "Dividend is paid on:", options: ['Debentures', 'Loans', 'Shares', 'Bonds'], answer: 2 },
    { unit: "Unit II", q: "Which share carries voting rights?", options: ['Preference share', 'Equity share', 'Debenture', 'Bond'], answer: 1 },
    { unit: "Unit II", q: "Fixed interest is paid on:", options: ['Equity shares', 'Preference shares', 'Debentures', 'Bonus shares'], answer: 2 },
    { unit: "Unit II", q: "Preference shareholders get preference in:", options: ['Voting', 'Management', 'Dividend payment', 'Risk bearing'], answer: 2 },
    { unit: "Unit II", q: "Which is NOT a feature of equity shares?", options: ['Ownership', 'Fixed return', 'Voting right', 'High risk'], answer: 1 },
    { unit: "Unit II", q: "Cumulative preference shares mean:", options: ['Dividend is cancelled', 'Dividend accumulates', 'Dividend is variable', 'No dividend'], answer: 1 },
    { unit: "Unit II", q: "Convertible debentures can be converted into:", options: ['Cash', 'Loans', 'Shares', 'Reserves'], answer: 2 },
    { unit: "Unit II", q: "Debenture holders receive return in the form of:", options: ['Bonus', 'Dividend', 'Interest', 'Commission'], answer: 2 },
    { unit: "Unit II", q: "Which has first claim on company assets at winding up?", options: ['Equity shareholders', 'Preference shareholders', 'Debenture holders', 'Promoters'], answer: 2 },
    { unit: "Unit II", q: "An investor wants fixed income with low risk. Best option is:", options: ['Equity shares', 'Preference shares', 'Debentures', 'Bonus shares'], answer: 2 },
    { unit: "Unit II", q: "A company wants to raise funds without diluting ownership. It should issue:", options: ['Equity shares', 'Preference shares', 'Debentures', 'Bonus shares'], answer: 2 },
    { unit: "Unit II", q: "An unpaid dividend that accumulates relates to:", options: ['Equity shares', 'Non-cumulative preference shares', 'Cumulative preference shares', 'Debentures'], answer: 2 },
    { unit: "Unit II", q: "At the time of liquidation, who is paid first?", options: ['Equity shareholders', 'Preference shareholders', 'Debenture holders', 'Directors'], answer: 2 },
    { unit: "Unit II", q: "Break Even Point is the point of:", options: ['Maximum profit', 'Maximum loss', 'No profit no loss', 'High sales'], answer: 2 },
    { unit: "Unit II", q: "Contribution is calculated as:", options: ['Sales - Fixed cost', 'Sales - Variable cost', 'Fixed cost - Variable cost', 'Profit - Cost'], answer: 1 },
    { unit: "Unit II", q: "Fixed cost is:", options: ['Variable with output', 'Constant irrespective of output', 'Dependent on sales', 'Zero at BEP'], answer: 1 },
    { unit: "Unit II", q: "EOQ deals with:", options: ['Pricing decision', 'Inventory quantity', 'Wage calculation', 'Profit sharing'], answer: 1 },
    { unit: "Unit II", q: "Which cost is involved in EOQ?", options: ['Selling cost', 'Ordering cost', 'Advertising cost', 'Production cost'], answer: 1 },
    { unit: "Unit II", q: "Break even analysis is useful for:", options: ['Salary fixation', 'Profit planning', 'Wage payment', 'Tax calculation'], answer: 1 },
    { unit: "Unit II", q: "Which remains constant at all levels of output?", options: ['Variable cost', 'Fixed cost', 'Contribution', 'Sales'], answer: 1 },
    { unit: "Unit II", q: "EOQ aims to minimize:", options: ['Production cost', 'Inventory cost', 'Selling cost', 'Purchase cost'], answer: 1 },
    { unit: "Unit II", q: "At break even point, profit is:", options: ['Maximum', 'Minimum', 'Zero', 'Negative'], answer: 2 },
    { unit: "Unit II", q: "Which cost increases with increase in inventory?", options: ['Ordering cost', 'Carrying cost', 'Fixed cost', 'Selling cost'], answer: 1 },
    { unit: "Unit II", q: "EOQ is applicable mainly to:", options: ['Sales forecasting', 'Inventory management', 'Financial accounting', 'Marketing'], answer: 1 },
    { unit: "Unit II", q: "Fixed cost = ₹20,000, Selling price per unit = ₹50, Variable cost per unit = ₹30. Break Even Point (units) is:", options: ['500', '1,000', '2,000', '400'], answer: 1 },
    { unit: "Unit II", q: "Contribution per unit in the above data is:", options: ['₹10', '₹20', '₹30', '₹50'], answer: 1 },
    { unit: "Unit II", q: "Annual demand = 10,000 units, Ordering cost per order = ₹100, Carrying cost per unit = ₹2. EOQ is:", options: ['500', '1,000', '1,414', '2,000'], answer: 2 },
    { unit: "Unit II", q: "If demand increases, EOQ will:", options: ['Decrease', 'Remain same', 'Increase', 'Become zero'], answer: 2 },
    { unit: "Unit II", q: "Fixed capital is invested in:", options: ['Cash', 'Debtors', 'Machinery', 'Inventory'], answer: 2 },
    { unit: "Unit II", q: "Which of the following is a current asset?", options: ['Land', 'Building', 'Furniture', 'Stock'], answer: 3 },
    { unit: "Unit II", q: "Fixed deposits are mainly offered by:", options: ['Manufacturing firms', 'Banks', 'Wholesalers', 'Retailers'], answer: 1 },
    { unit: "Unit II", q: "Which capital ensures smooth day-to-day business operations?", options: ['Fixed capital', 'Share capital', 'Working capital', 'Reserve capital'], answer: 2 },
    { unit: "Unit II", q: "Fixed capital is called 'fixed' because it:", options: ['Remains constant in value', 'Is permanently invested', 'Cannot be sold', 'Earns fixed returns'], answer: 1 },
    { unit: "Unit II", q: "One major advantage of fixed deposits is:", options: ['High risk', 'Market fluctuation', 'Guaranteed return', 'Ownership rights'], answer: 2 },
    { unit: "Unit II", q: "Insufficient working capital results in:", options: ['Higher profits', 'Smooth production', 'Business inefficiency', 'Increased liquidity'], answer: 2 },
    { unit: "Unit II", q: "A firm purchases a new machine worth ₹5,00,000. This is an example of:", options: ['Working capital', 'Fixed capital', 'Reserve fund', 'Revenue expenditure'], answer: 1 },
    { unit: "Unit II", q: "Cash used to pay employee salaries comes from:", options: ['Fixed capital', 'Share capital', 'Working capital', 'Long-term loan'], answer: 2 },
    { unit: "Unit II", q: "Idle business funds invested safely for 2 years should be placed in:", options: ['Shares', 'Debentures', 'Fixed deposits', 'Inventory'], answer: 2 },
    { unit: "Unit II", q: "If current assets are ₹1,50,000 and current liabilities are ₹90,000, working capital is:", options: ['₹60,000', '₹90,000', '₹1,50,000', '₹2,40,000'], answer: 0 },
    { unit: "Unit II", q: "Which business requires high fixed capital?", options: ['Retail shop', 'Manufacturing plant', 'Trading firm', 'Service center'], answer: 1 },
    { unit: "Unit II", q: "Excess working capital may lead to:", options: ['Shortage of cash', 'Inefficient fund utilization', 'Production stoppage', 'Business failure'], answer: 1 },
    { unit: "Unit II", q: "Fixed deposits are preferred over shares because they are:", options: ['High return', 'Market linked', 'Low risk', 'Transferable'], answer: 2 },
    { unit: "Unit II", q: "Conversion of fixed capital into cash is:", options: ['Easy', 'Immediate', 'Difficult', 'Profitable'], answer: 2 },
  ],

  // UNIT III - Human Resource Management
  unit3: [
    { unit: "Unit III", q: "HRM deals with management of:", options: ['Money', 'Machines', 'Materials', 'Men'], answer: 3 },
    { unit: "Unit III", q: "HRM considers employees as:", options: ['Liabilities', 'Costs', 'Assets', 'Burden'], answer: 2 },
    { unit: "Unit III", q: "The full form of HRM is:", options: ['Human Relation Management', 'Human Resource Maintenance', 'Human Resource Management', 'Human Recruitment Management'], answer: 2 },
    { unit: "Unit III", q: "Recruitment and selection fall under:", options: ['Procurement', 'Maintenance', 'Integration', 'Compensation'], answer: 0 },
    { unit: "Unit III", q: "Main aim of HRM is to:", options: ['Reduce employee strength', 'Increase profits only', 'Achieve organizational goals through people', 'Replace technology'], answer: 2 },
    { unit: "Unit III", q: "Which of the following is a personal objective of HRM?", options: ['Productivity', 'Profit maximization', 'Employee satisfaction', 'Cost reduction'], answer: 2 },
    { unit: "Unit III", q: "Training and development is related to:", options: ['Procurement', 'Development', 'Maintenance', 'Integration'], answer: 1 },
    { unit: "Unit III", q: "Social objectives of HRM include:", options: ['Wage fixation', 'Employee discipline', 'Ethical practices', 'Cost control'], answer: 2 },
    { unit: "Unit III", q: "Functional objectives of HRM focus on:", options: ['Employee welfare', 'HR department efficiency', 'Social responsibility', 'Personal growth'], answer: 1 },
    { unit: "Unit III", q: "A company hires skilled workers to improve productivity. This reflects:", options: ['Social objective', 'Personal objective', 'Organizational objective', 'Individual objective'], answer: 2 },
    { unit: "Unit III", q: "Providing safety measures and medical facilities comes under:", options: ['Development', 'Procurement', 'Maintenance', 'Integration'], answer: 2 },
    { unit: "Unit III", q: "Encouraging employee participation in decision making helps in:", options: ['Procurement', 'Integration', 'Compensation', 'Development'], answer: 1 },
    { unit: "Unit III", q: "A firm focusing on employee career growth is fulfilling:", options: ['Social objective', 'Functional objective', 'Personal objective', 'Organizational objective'], answer: 2 },
    { unit: "Unit III", q: "Treating employees fairly and ethically supports:", options: ['Organizational aim', 'Social objective', 'Functional objective', 'Technical objective'], answer: 1 },
    { unit: "Unit III", q: "HRM contributes to organizational success mainly by:", options: ['Increasing capital', 'Reducing taxes', 'Effective utilization of human resources', 'Improving technology'], answer: 2 },
  ],

};